import type { Request, Response } from "express"
import { query } from "../db"
import { hashPassword } from "../utils/auth"

export const createPatient = async (req: Request, res: Response) => {
	// These fields come from your Postman/Frontend request
	const {
		first_name,
		last_name,
		email,
		document_id,
		phone,
		birthdate,
		gender,
		address,
		blood_type,
		allergies,
	} = req.body

	// Validation
	if (
		!first_name ||
		!last_name ||
		!email ||
		!document_id ||
		!phone ||
		!birthdate ||
		!gender ||
		!address
	) {
		return res.status(400).json({
			error:
				"Missing required fields: first_name, last_name, email, document_id, phone, birthdate, gender and address are mandatory.",
		})
	}

	try {
		// Construct the full name for the users table 'name' column
		const fullName = `${first_name} ${last_name}`

		// Use a secure temporary password logic or a hardcoded one for now
		// Ideally, you'd send an email to the patient to reset this immediately
		const temporaryPassword = "TempPassword123!"
		const hashedPassword = await hashPassword(temporaryPassword)

		// 1. Insert into users table
		// The Trigger 'trg_create_patient_on_signup' will automatically
		// create the record in the 'patients' table after this query.
		const result = await query(
			`INSERT INTO users (name, email, password, role, document_id, phone, birthdate, gender, address, blood_type, allergies) 
             VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11) 
             RETURNING id, name, email, role, document_id, 
             TO_CHAR(created_at, 'YYYY-MM-DD HH24:MI:SS') as created_at,
			 TO_CHAR(birthdate, 'DD/MM/YYYY') as birthdate`,
			[
				fullName,
				email.toLowerCase(),
				hashedPassword,
				"Paciente",
				document_id,
				phone,
				birthdate,
				gender,
				address,
				blood_type || null,
				allergies || [],
			],
		)

		// 2. Response
		res.status(201).json({
			message:
				"Patient user created successfully. Clinical profile generated by database trigger.",
			user: result.rows[0],
			temporaryPassword, // Returned so staff can give it to the patient
		})
	} catch (error) {
		console.error("Error in createPatient (User Insert):", error)
		res.status(500).json({ error: "Internal server error" })
	}
}

// 2. Get all Patients
export const getAllPatients = async (_req: Request, res: Response) => {
	try {
		// We join with users to potentially show account status if needed
		const result = await query(
			`SELECT * FROM patients ORDER BY last_name ASC`,
			[],
		)
		res.json({ patients: result.rows })
	} catch (error) {
		console.error("Error fetching patients:", error)
		res.status(500).json({ error: "Internal server error" })
	}
}

// 2. Get Patients assigned to the logged-in Doctor
export const getDoctorPatients = async (req: Request, res: Response) => {
	const doctorId = req.user?.document_id

	if (!doctorId) {
		return res
			.status(401)
			.json({ error: "No autorizado. ID de médico no encontrado." })
	}

	try {
		// Buscamos pacientes que cumplan AL MENOS una de las tres condiciones con este médico
		const result = await query(
			`SELECT p.* FROM patients p
             WHERE EXISTS (
                 SELECT 1 FROM medical_records mr 
                 WHERE mr.patient_id = p.document_id AND mr.doctor_id = $1
             )
             OR EXISTS (
                 SELECT 1 FROM appointments a 
                 WHERE a.patient_id = p.document_id AND a.doctor_id = $1
             )
             OR EXISTS (
                 SELECT 1 FROM surgeries s 
                 WHERE s.patient_id = p.document_id AND s.doctor_id = $1
             )
             ORDER BY p.last_name ASC`,
			[doctorId],
		)

		res.json({
			count: result.rowCount,
			patients: result.rows,
		})
	} catch (error) {
		console.error("Error fetching doctor patients:", error)
		res.status(500).json({ error: "Internal server error" })
	}
}

// 3. Get Patient by document_id
export const getPatientById = async (req: Request, res: Response) => {
	const { id } = req.params

	try {
		const result = await query(
			`SELECT * FROM patients WHERE document_id = $1`,
			[id],
		)

		if (result.rowCount === 0) {
			return res.status(404).json({ error: "Patient not found." })
		}

		res.json(result.rows[0])
	} catch (error) {
		console.error("Error fetching patient:", error)
		res.status(500).json({ error: "Internal server error" })
	}
}

// 4. Update Patient
export const updatePatient = async (req: Request, res: Response) => {
	const { id } = req.params
	const updates = req.body

	const allowedFields = [
		"first_name",
		"last_name",
		"email",
		"phone",
		"birthdate",
		"gender",
		"address",
		"blood_type",
		"allergies",
	]
	const keys = Object.keys(updates).filter((key) => allowedFields.includes(key))

	if (keys.length === 0)
		return res.status(400).json({ error: "No valid fields provided" })

	const setClause = keys.map((key, i) => `${key} = $${i + 1}`).join(", ")
	const values = keys.map((key) => updates[key])

	// Add document_id as the last parameter for the WHERE clause
	values.push(id)

	try {
		const result = await query(
			`UPDATE patients 
             SET ${setClause}, updated_at = NOW()
             WHERE document_id = $${values.length}
             RETURNING *,
             TO_CHAR(created_at, 'YYYY-MM-DD HH24:MI:SS') as created_at, 
             TO_CHAR(updated_at, 'YYYY-MM-DD HH24:MI:SS') as updated_at`,
			values,
		)

		if (result.rowCount === 0)
			return res.status(404).json({ error: "Patient not found" })

		res.json({
			patient: result.rows[0],
			message: "Patient updated successfully",
		})
	} catch (error) {
		console.error("Error updating patient:", error)
		res.status(500).json({ error: "Internal server error" })
	}
}

// 5. Delete Patient
export const deletePatient = async (req: Request, res: Response) => {
	const { id } = req.params

	try {
		const result = await query(`DELETE FROM patients WHERE document_id = $1`, [
			id,
		])

		if (result.rowCount === 0)
			return res.status(404).json({ error: "Patient not found" })

		res.json({ message: "Patient deleted successfully" })
	} catch (error: any) {
		if (error.code === "23503") {
			return res.status(409).json({
				error:
					"No se puede eliminar el paciente porque tiene registros asociados (citas, evoluciones, etc.).",
			})
		}
		console.error("Error deleting patient:", error)
		res.status(500).json({ error: "Internal server error" })
	}
}
