import type { Request, Response } from "express"
import { query } from "../db.js"
import { sendVerificationEmailToUser } from "../services/EmailVerificationService.js"
import { hashPassword } from "../utils/auth.js"

function isPostgresError(
	error: unknown,
): error is {
	code?: string
	constraint?: string
	detail?: string
	message?: string
} {
	return (
		typeof error === "object" &&
		error !== null &&
		"code" in error &&
		typeof (error as { code?: unknown }).code === "string"
	)
}

function getFriendlyDuplicateEmailMessage(detail?: string, constraint?: string) {
	// Most common from your log:
	// Key (email)=(...) already exists.
	if (constraint === "users_email_key") {
		return "This email is already in use. Please use another email."
	}
	if (detail?.toLowerCase().includes("email")) {
		return "This email is already in use. Please use another email."
	}
	return "Duplicate value. Please verify your submitted information."
}

export const createPatient = async (req: Request, res: Response) => {
	// These fields come from your Postman/Frontend request
	const {
		first_name,
		last_name,
		email,
		document_id,
		phone,
		birthdate,
		gender,
		address,
		blood_type,
		allergies,
	} = req.body

	// Validation
	if (
		!first_name ||
		!last_name ||
		!email ||
		!document_id ||
		!phone ||
		!birthdate ||
		!gender ||
		!address
	) {
		return res.status(400).json({
			error:
				"Missing required fields: first_name, last_name, email, document_id, phone, birthdate, gender and address are mandatory.",
		})
	}

	try {
		// Construct the full name for the users table 'name' column
		const fullName = `${first_name} ${last_name}`

		// Use a secure temporary password logic or a hardcoded one for now
		// Ideally, you'd send an email to the patient to reset this immediately
		const temporaryPassword = "TempPassword123!"
		const hashedPassword = await hashPassword(temporaryPassword)

		// 1. Insert into users table
		// The Trigger 'trg_create_patient_on_signup' will automatically
		// create the record in the 'patients' table after this query.
		const result = await query(
			`INSERT INTO users (name, email, password, role, document_id, phone, birthdate, gender, address, blood_type, allergies) 
             VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11) 
             RETURNING id, name, email, role, document_id, 
             TO_CHAR(created_at, 'YYYY-MM-DD HH24:MI:SS') as created_at,
			 TO_CHAR(birthdate, 'DD/MM/YYYY') as birthdate`,
			[
				fullName,
				email.toLowerCase(),
				hashedPassword,
				"Paciente",
				document_id,
				phone,
				birthdate,
				gender,
				address,
				blood_type || null,
				allergies || [],
			],
		)

		const created = result.rows[0] as { id: number; name: string; email: string }
		try {
			await sendVerificationEmailToUser(
				created.id,
				String(created.email).toLowerCase(),
				created.name,
			)
		} catch (err) {
			console.error("Email verification send failed (create patient):", err)
		}

		// 2. Response
		res.status(201).json({
			message:
				"Patient user created successfully. Clinical profile generated by database trigger.",
			user: result.rows[0],
			temporaryPassword, // Returned so staff can give it to the patient
		})
	} catch (error) {
		console.error("Error in createPatient (User Insert):", error)
		if (isPostgresError(error) && error.code === "23505") {
			return res.status(409).json({
				error: getFriendlyDuplicateEmailMessage(
					error.detail,
					error.constraint,
				),
			})
		}
		return res.status(500).json({ error: "Internal server error" })
	}
}

// 2. Get all Patients (Admin: optional ?doctor_id= filters by medical_records author)
export const getAllPatients = async (req: Request, res: Response) => {
	try {
		const doctorIdParam =
			req.user?.role === "Admin"
				? (req.query.doctor_id as string | undefined)
				: undefined
		const doctorFilter =
			doctorIdParam &&
			doctorIdParam !== "all" &&
			String(doctorIdParam).trim() !== ""
				? String(doctorIdParam).trim()
				: null

		const params: string[] = []
		let doctorExistsClause = ""
		if (doctorFilter) {
			doctorExistsClause = ` AND EXISTS (
				SELECT 1 FROM medical_records mr
				WHERE mr.patient_id = p.document_id AND mr.doctor_id = $1
			)`
			params.push(doctorFilter)
		}

		const result = await query(
			`SELECT p.*,
				(
					SELECT COALESCE(string_agg(name, ', ' ORDER BY name), '')
					FROM (
						SELECT DISTINCT u.name AS name
						FROM medical_records mr2
						JOIN users u ON mr2.doctor_id = u.document_id
						WHERE mr2.patient_id = p.document_id
					) d
				) AS attending_doctors,
				(
					NOT EXISTS (
						SELECT 1 FROM medical_records mr_u WHERE mr_u.patient_id = p.document_id
					)
					AND NOT EXISTS (
						SELECT 1 FROM appointments a_u WHERE a_u.patient_id = p.document_id
					)
					AND NOT EXISTS (
						SELECT 1 FROM surgeries s_u WHERE s_u.patient_id = p.document_id
					)
				) AS is_unassigned
			FROM patients p
			WHERE 1=1
			${doctorExistsClause}
			ORDER BY is_unassigned DESC, p.last_name ASC`,
			params,
		)
		res.json({ patients: result.rows })
	} catch (error) {
		console.error("Error fetching patients:", error)
		res.status(500).json({ error: "Internal server error" })
	}
}

// 2. Get Patients assigned to the logged-in Doctor
export const getDoctorPatients = async (req: Request, res: Response) => {
	const doctorId = req.user?.document_id

	if (!doctorId) {
		return res
			.status(401)
			.json({ error: "No autorizado. ID de médico no encontrado." })
	}

	try {
		// Pacientes vinculados a este médico (evolución, cita o cirugía) O pacientes sin
		// ningún vínculo clínico aún (recién creados — visibles para poder asignar la primera cita/cirugía).
		const result = await query(
			`SELECT p.*,
				(
					SELECT COALESCE(string_agg(name, ', ' ORDER BY name), '')
					FROM (
						SELECT DISTINCT u.name AS name
						FROM medical_records mr2
						JOIN users u ON mr2.doctor_id = u.document_id
						WHERE mr2.patient_id = p.document_id
					) d
				) AS attending_doctors,
				(
					NOT EXISTS (
						SELECT 1 FROM medical_records mr0 WHERE mr0.patient_id = p.document_id
					)
					AND NOT EXISTS (
						SELECT 1 FROM appointments a0 WHERE a0.patient_id = p.document_id
					)
					AND NOT EXISTS (
						SELECT 1 FROM surgeries s0 WHERE s0.patient_id = p.document_id
					)
				) AS is_unassigned
			FROM patients p
			WHERE EXISTS (
				SELECT 1 FROM medical_records mr
				WHERE mr.patient_id = p.document_id AND mr.doctor_id = $1
			)
			OR EXISTS (
				SELECT 1 FROM appointments a
				WHERE a.patient_id = p.document_id AND a.doctor_id = $1
			)
			OR EXISTS (
				SELECT 1 FROM surgeries s
				WHERE s.patient_id = p.document_id AND s.doctor_id = $1
			)
			OR (
				NOT EXISTS (
					SELECT 1 FROM medical_records mr3 WHERE mr3.patient_id = p.document_id
				)
				AND NOT EXISTS (
					SELECT 1 FROM appointments a3 WHERE a3.patient_id = p.document_id
				)
				AND NOT EXISTS (
					SELECT 1 FROM surgeries s3 WHERE s3.patient_id = p.document_id
				)
			)
			ORDER BY is_unassigned DESC, p.last_name ASC`,
			[doctorId],
		)

		res.json({
			count: result.rowCount,
			patients: result.rows,
		})
	} catch (error) {
		console.error("Error fetching doctor patients:", error)
		res.status(500).json({ error: "Internal server error" })
	}
}

// 3. Get Patient by document_id
export const getPatientById = async (req: Request, res: Response) => {
	const { id } = req.params

	try {
		const result = await query(
			`SELECT * FROM patients WHERE document_id = $1`,
			[id],
		)

		if (result.rowCount === 0) {
			return res.status(404).json({ error: "Patient not found." })
		}

		res.json(result.rows[0])
	} catch (error) {
		console.error("Error fetching patient:", error)
		res.status(500).json({ error: "Internal server error" })
	}
}

// 4. Update Patient
export const updatePatient = async (req: Request, res: Response) => {
	const { id } = req.params
	const updates = req.body

	const allowedFields = [
		"first_name",
		"last_name",
		"email",
		"phone",
		"birthdate",
		"gender",
		"address",
		"blood_type",
		"allergies",
	]
	const keys = Object.keys(updates).filter((key) => allowedFields.includes(key))

	if (keys.length === 0)
		return res.status(400).json({ error: "No valid fields provided" })

	const setClause = keys.map((key, i) => `${key} = $${i + 1}`).join(", ")
	const values = keys.map((key) => updates[key])

	// Add document_id as the last parameter for the WHERE clause
	values.push(id)

	try {
		const result = await query(
			`UPDATE patients 
             SET ${setClause}, updated_at = NOW()
             WHERE document_id = $${values.length}
             RETURNING *,
             TO_CHAR(created_at, 'YYYY-MM-DD HH24:MI:SS') as created_at, 
             TO_CHAR(updated_at, 'YYYY-MM-DD HH24:MI:SS') as updated_at`,
			values,
		)

		if (result.rowCount === 0)
			return res.status(404).json({ error: "Patient not found" })

		res.json({
			patient: result.rows[0],
			message: "Patient updated successfully",
		})
	} catch (error) {
		console.error("Error updating patient:", error)
		if (isPostgresError(error) && error.code === "23505") {
			return res.status(409).json({
				error: getFriendlyDuplicateEmailMessage(
					error.detail,
					error.constraint,
				),
			})
		}
		return res.status(500).json({ error: "Internal server error" })
	}
}

// 5. Delete Patient
export const deletePatient = async (req: Request, res: Response) => {
	const { id } = req.params

	try {
		const result = await query(`DELETE FROM patients WHERE document_id = $1`, [
			id,
		])

		if (result.rowCount === 0)
			return res.status(404).json({ error: "Patient not found" })

		res.json({ message: "Patient deleted successfully" })
	} catch (error) {
		if (isPostgresError(error) && error.code === "23503") {
			return res.status(409).json({
				error:
					"No se puede eliminar el paciente porque tiene registros asociados (citas, evoluciones, etc.).",
			})
		}
		console.error("Error deleting patient:", error)
		res.status(500).json({ error: "Internal server error" })
	}
}
